stages:
  - deploy
  - run

build and push image:
  stage: deploy
  only:
    - master
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest everysize # --tag $CI_REGISTRY_IMAGE:$COMMIT_COUNT
    - docker push $CI_REGISTRY_IMAGE:latest # $CI_REGISTRY_IMAGE:$COMMIT_COUNT

run on freebox:
  stage: run
  image: registry.gitlab.com/kibalabs/kiba/docker-images/ssh-able:latest
  variables:
    RUNNABLE_DIRECTORY: "~/deployments/$CI_PROJECT_PATH/$CI_COMMIT_SHORT_SHA"
  script:
    - run-ssh-command "$FREEBOX_SSH_KEY" "$FREEBOX_USER" "$FREEBOX_URL" "
        rm -rf $RUNNABLE_DIRECTORY &&
        git clone $CI_REPOSITORY_URL $RUNNABLE_DIRECTORY &&
        cd $RUNNABLE_DIRECTORY &&
        ./run.sh
      "
